# Generated by Django 2.0.6 on 2018-11-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181128_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WikiPage',
            new_name='WikiPages',
        ),
    ]
